version: '3.8'
services:
  app:
    image: aoirint/liveinfo_api_middleware
    build: .
    restart: always
    environment:
      YTLIVE_CHANNEL_ID: ${YTLIVE_CHANNEL_ID}
      YTLIVE_API_KEY: ${YTLIVE_API_KEY}
      YTLIVE_DUMP_PATH: ${YTLIVE_DUMP_PATH}
      NICOLIVE_COMMUNITY_ID: ${NICOLIVE_COMMUNITY_ID}
      NICOLIVE_DUMP_PATH: ${NICOLIVE_DUMP_PATH}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS}
    volumes:
      - "${HOST_DATA_DIR}:/data"
    ports:
      - "${HOST_PORT}:8000"
